app_welcom:
    pattern:  /
    defaults: { _controller: AppBundle:Shop:index }

_security_login:
    pattern:  /login
    defaults: { _controller: AppBundle:Shop:login }

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout

app_register:
    pattern:  /register
    defaults: { _controller: AppBundle:Shop:register }
    requirements:
        _method:  GET

app_registration:
    pattern:  /registration
    defaults: { _controller: AppBundle:Shop:registration }
    requirements:
        _method:  POST
                       