AppBundle\Entity\User:
    type: entity
    repositoryClass: AppBundle\Repository\UserRepository
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 255
            unique: true
    
        password:
            type: string
            length: 500
            
        salt:
            type: string
            length: 255
            
        email:
            type: string
            length: 255
        
        isActive:
            type: string
            length: 25
        
    